### ISSUE TITLE
KeyError: 'payload'

### ISSUE THREAD

**Issue by CiaranYoung** [Ayan-Nalawade/Chat#2]
When I ran the demo program in replit, it reported this error to me:
```py
`Using /home/runner/Chat/.pythonlibs/lib/python3.10/site-packages for installing additional dependencies, if required
Traceback (most recent call last):
  File "main.py", line 592, in <module>
    client = Client(tokens[count])
  File "main.py", line 107, in __init__
    self.setup_connection()
  File "main.py", line 112, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "main.py", line 149, in get_next_data
    self.viewer = next_data["props"]["pageProps"]["payload"]["viewer"]
KeyError: 'payload'`
```
I haven't made any changes to the original code, why is this problem

**Comment by Ayan-Nalawade** [comment]
Hi, currently the demo is not working (as said on the GitHub page) on replit, the error you are having is as the version is old. If you want to get it to work, you will have to add your own tokens or auth and then update the modules using the `requirements.txt` file in this github, or manually installing the files using the terminal
