### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Fr4Ckt3r** [Ayan-Nalawade/Chat#3]
``567cd4f61cdf75f7f3dbc9b4d406d59604fb8809 > Claude-2-100k : Can you say amongus?
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (1/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (1/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (2/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (2/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (3/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (3/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (4/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (4/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (5/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (5/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (6/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (7/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (6/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (8/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (7/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (9/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (8/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json. Retrying (10/10)...
Exception in thread Thread-30 (get_bot_thread):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (9/10)...
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dark\AppData\Roaming\Python\Python311\site-packages\poe.py", line 260, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dark\AppData\Roaming\Python\Python311\site-packages\poe.py", line 237, in get_bot
    data = request_with_retries(self.session.get, url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dark\AppData\Roaming\Python\Python311\site-packages\poe.py", line 79, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/GPT-4-32k.json too many times.
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json. Retrying (10/10)...
Exception in thread Thread-29 (get_bot_thread):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dark\AppData\Roaming\Python\Python311\site-packages\poe.py", line 260, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dark\AppData\Roaming\Python\Python311\site-packages\poe.py", line 237, in get_bot
    data = request_with_retries(self.session.get, url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dark\AppData\Roaming\Python\Python311\site-packages\poe.py", line 79, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/_next/data/mUDtGgcLPIKVxstRPCb2b/ChatGPT-16k.json too many times.
 Sure, I can say "amongus."``

 As you see, it seems to work, but this spamming is quite annoying

**Comment by Ayan-Nalawade** [comment]
It's not spamming, it's returning an error, I would suspect that this is happening due to outdated modules, OR it may be occurring because poe.com suspects that your IP address may be a bot, you might need to wait a bit and try again
